from __future__ import annotations

import importlib.util
import io
import sys
from pathlib import Path
from types import ModuleType, SimpleNamespace

import pytest

from tests._paths import REPO_ROOT


def _load_generator_module():
    script_path = REPO_ROOT / "docs" / "gen_ref_pages.py"
    spec = importlib.util.spec_from_file_location("boxmot_gen_ref_pages", script_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


generator = _load_generator_module()


def test_discovery_maps_packages_and_parses_docstrings_without_importing(tmp_path):
    package_root = tmp_path / "sample"
    nested_root = package_root / "nested"
    nested_root.mkdir(parents=True)
    (package_root / "__init__.py").write_text('"""Sample package."""\n', encoding="utf-8")
    (package_root / "public.py").write_text(
        '"""Public module."""\n\n'
        "from optional_backend import ImportedAlias\n\n"
        "PUBLIC_VALUE = 1\n\n"
        "def local_function():\n"
        "    pass\n\n"
        'raise RuntimeError("must not execute")\n',
        encoding="utf-8",
    )
    (package_root / "_internal.py").write_text('"""Internal module."""\n', encoding="utf-8")
    (nested_root / "__init__.py").write_text("", encoding="utf-8")
    (nested_root / "worker.py").write_text('"""Nested worker."""\n', encoding="utf-8")
    (nested_root / "__main__.py").write_text('raise RuntimeError("skip entry points")\n', encoding="utf-8")

    references = generator.discover_modules(package_root)
    by_identifier = {reference.identifier: reference for reference in references}

    assert tuple(by_identifier) == (
        "sample",
        "sample._internal",
        "sample.nested",
        "sample.nested.worker",
        "sample.public",
    )
    assert by_identifier["sample"].page_path == Path("reference/sample/index.md")
    assert by_identifier["sample.nested"].page_path == Path("reference/sample/nested/index.md")
    assert by_identifier["sample.public"].page_path == Path("reference/sample/public.md")
    assert by_identifier["sample.public"].docstring == "Public module."
    assert by_identifier["sample.nested"].docstring is None
    assert by_identifier["sample.public"].local_members == ("PUBLIC_VALUE", "local_function")


def test_discovery_is_deterministic(tmp_path):
    package_root = tmp_path / "sample"
    package_root.mkdir()
    (package_root / "zeta.py").write_text("", encoding="utf-8")
    (package_root / "alpha.py").write_text("", encoding="utf-8")

    first = generator.discover_modules(package_root)
    second = generator.discover_modules(package_root)

    assert first == second
    assert [reference.identifier for reference in first] == ["sample.alpha", "sample.zeta"]


def test_invalid_python_reports_the_source_path(tmp_path):
    package_root = tmp_path / "sample"
    package_root.mkdir()
    broken_path = package_root / "broken.py"
    broken_path.write_text("def broken(:\n", encoding="utf-8")

    with pytest.raises(ValueError, match=r"Unable to parse Python module .*broken\.py"):
        generator.discover_modules(package_root)


@pytest.mark.parametrize(
    ("source_name", "local_members", "expected_members"),
    [
        ("sample.py", (), "      members: false\n"),
        ("sample.py", ("run",), "      members:\n        - run\n"),
        ("__init__.py", (), "      members: false\n"),
        ("__init__.py", ("create", "DEFAULT"), "      members:\n        - create\n        - DEFAULT\n"),
    ],
)
def test_module_page_configures_mkdocstrings_members(
    tmp_path,
    source_name,
    local_members,
    expected_members,
):
    source_path = tmp_path / source_name
    reference = generator.ModuleReference(
        source_path=source_path,
        identifier="sample",
        page_path=Path("reference/sample.md"),
        nav_parts=("sample",),
        docstring="Sample module.",
        local_members=local_members,
    )

    assert generator.render_module_page(reference) == (
        "---\n"
        "search:\n"
        "  boost: 0.5\n"
        "---\n\n"
        "<!-- Generated by docs/gen_ref_pages.py; do not edit. -->\n\n"
        "::: sample\n"
        "    options:\n"
        "      heading_level: 1\n"
        "      show_if_no_docstring: true\n"
        "      show_root_full_path: true\n"
        "      show_root_heading: true\n"
        "      show_source: false\n"
        "      show_symbol_type_heading: true\n"
        "      show_symbol_type_toc: true\n"
        f"{expected_members}"
    )


def test_discovery_rejects_identifier_and_page_collisions(tmp_path):
    identifier_root = tmp_path / "identifier" / "sample"
    (identifier_root / "worker").mkdir(parents=True)
    (identifier_root / "worker.py").write_text("", encoding="utf-8")
    (identifier_root / "worker" / "__init__.py").write_text("", encoding="utf-8")

    with pytest.raises(ValueError, match="same identifier"):
        generator.discover_modules(identifier_root)

    page_root = tmp_path / "page" / "sample"
    page_root.mkdir(parents=True)
    (page_root / "__init__.py").write_text("", encoding="utf-8")
    (page_root / "index.py").write_text("", encoding="utf-8")

    with pytest.raises(ValueError, match="same reference page"):
        generator.discover_modules(page_root)


def test_generate_reference_writes_pages_navigation_and_edit_paths(tmp_path, monkeypatch):
    package_root = tmp_path / "sample"
    package_root.mkdir()
    (package_root / "__init__.py").write_text('"""Sample package."""\n', encoding="utf-8")
    (package_root / "worker.py").write_text("def run():\n    pass\n", encoding="utf-8")

    generated: dict[Path, str] = {}
    edit_paths: dict[Path, Path] = {}
    inclusion_level = SimpleNamespace(EXCLUDED=object(), UNDEFINED=object())
    generated_nav = SimpleNamespace(inclusion=inclusion_level.UNDEFINED)

    class GeneratedFile(io.StringIO):
        def __init__(self, path):
            super().__init__()
            self.path = Path(path)

        def close(self):
            if not self.closed:
                generated[self.path] = self.getvalue()
            super().close()

    class FakeNav:
        def __init__(self):
            self.entries = []

        def __setitem__(self, parts, target):
            if isinstance(parts, str):
                parts = (parts,)
            self.entries.append((parts, target))

        def build_literate_nav(self):
            return [f"{'    ' * (len(parts) - 1)}* [{parts[-1]}]({target})\n" for parts, target in self.entries]

    fake_gen_files = ModuleType("mkdocs_gen_files")
    fake_gen_files.Nav = FakeNav
    fake_gen_files.open = lambda path, _mode: GeneratedFile(path)
    fake_gen_files.set_edit_path = lambda path, edit_path: edit_paths.__setitem__(Path(path), Path(edit_path))
    fake_gen_files.files = SimpleNamespace(get_file_from_path=lambda _path: generated_nav)

    fake_mkdocs = ModuleType("mkdocs")
    fake_mkdocs.__path__ = []
    fake_structure = ModuleType("mkdocs.structure")
    fake_structure.__path__ = []
    fake_structure_files = ModuleType("mkdocs.structure.files")
    fake_structure_files.InclusionLevel = inclusion_level

    monkeypatch.setitem(sys.modules, "mkdocs_gen_files", fake_gen_files)
    monkeypatch.setitem(sys.modules, "mkdocs", fake_mkdocs)
    monkeypatch.setitem(sys.modules, "mkdocs.structure", fake_structure)
    monkeypatch.setitem(sys.modules, "mkdocs.structure.files", fake_structure_files)

    generator.generate_reference(package_root, Path("reference"), tmp_path)

    assert set(generated) == {
        Path("reference/index.md"),
        Path("reference/sample/index.md"),
        Path("reference/sample/worker.md"),
        Path("reference/SUMMARY.md"),
    }
    assert "* [sample](sample/index.md)" in generated[Path("reference/SUMMARY.md")]
    assert "    * [worker](sample/worker.md)" in generated[Path("reference/SUMMARY.md")]
    assert "show_if_no_docstring: true" in generated[Path("reference/sample/worker.md")]
    assert edit_paths[Path("reference/index.md")] == Path("gen_ref_pages.py")
    assert edit_paths[Path("reference/sample/worker.md")] == Path("../sample/worker.py")
    assert generated_nav.inclusion is inclusion_level.EXCLUDED


def test_real_tree_contains_representative_reference_targets():
    references = generator.discover_modules(REPO_ROOT / "boxmot")
    identifiers = {reference.identifier for reference in references}
    page_paths = {reference.page_path for reference in references}

    assert {
        "boxmot",
        "boxmot.structures",
        "boxmot.pipelines",
        "boxmot.trackers.registry",
        "boxmot.datasets",
    } <= identifiers
    assert len(identifiers) == len(references)
    assert len(page_paths) == len(references)
