id: dancetrack

dataset:
  id: dancetrack
  root: "boxmot/datasets/mot/test1"
  layout: mot
  box_type: aabb
  splits:
    val: "val"
  default_split: val
  classes:
    1: pedestrian

evaluation:
  classes:
    - name: pedestrian
      dataset_id: 1
      detector_id: 0
      detector_name: person

download:
  dataset: "https://huggingface.co/datasets/noahcao/dancetrack/resolve/main/test1.zip"
  runs: ""

detector:
  id: yolox_x_dancetrack
  model: "models/yolox_x_dancetrack.pt"
  url: "https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_dancetrack.pt"
  imgsz: [800, 1440]
  conf: 0.01
  classes:
    0: person

reid:
  id: lmbn_n_duke
  model: "models/lmbn_n_duke.pt"
  url: "https://github.com/mikel-brostrom/boxmot/releases/download/v21.0.0/lmbn_n_duke.pt"
  device: ""
  half: true
  preprocess: resize
