id: dota8-mot

download:
  runs_url: ""
  dataset_url: ""

storage:
  root: "assets/DOTA8-MOT"
  split: "train"

evaluation:
  box_type: obb
  layout: mmot_rgb
  tracker_eval: mmot_rgb
  classes:
    eval:
      1: plane
      # 2: ship
      # 3: storage tank
      # 4: baseball diamond
      5: tennis court
      # 6: basketball court
      # 7: ground track field
      # 8: harbor
      # 9: bridge
      # 10: large vehicle
      11: small vehicle
      # 12: helicopter
      # 13: roundabout
      # 14: soccer ball field
      15: swimming pool
    distractor: {}
    mapping: {}

detector:
  default_model: "models/yolo11s-obb.pt"
  imgsz: [1024, 1024]
  conf: 0.2
  classes:
    0: plane
    1: ship
    2: storage tank
    3: baseball diamond
    4: tennis court
    5: basketball court
    6: ground track field
    7: harbor
    8: bridge
    9: large vehicle
    10: small vehicle
    11: helicopter
    12: roundabout
    13: soccer ball field
    14: swimming pool
