id: mot17-mini

dataset:
  id: mot17-mini
  root: "assets/MOT17-mini"
  layout: mot
  box_type: aabb
  splits:
    train: "train"
  default_split: train
  classes:
    1: pedestrian
  distractors:
    2: person_on_vehicle
    7: static_person
    8: distractor
    12: reflection

evaluation:
  classes:
    - name: pedestrian
      dataset_id: 1
      detector_id: 0
      detector_name: person
  ignore_dataset_ids: [2, 7, 8, 12]

download:
  runs: ""

detector:
  id: yolox_x_mot17_ablation
  model: "models/yolox_x_MOT17_ablation.pt"
  url: "https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_MOT17_ablation.pt"
  imgsz: [800, 1440]
  conf: 0.01
  classes:
    0: person

reid:
  id: lmbn_n_duke
  model: "models/lmbn_n_duke.pt"
  url: "https://github.com/mikel-brostrom/boxmot/releases/download/v21.0.0/lmbn_n_duke.pt"
  device: ""
  half: true
  preprocess: resize
