id: mot20

dataset:
  id: mot20
  root: "boxmot/datasets/mot/MOT20"
  layout: mot
  box_type: aabb
  splits:
    train: "train"
    test: "test"
    ablation: "ablation"
  default_split: ablation
  no_gt_splits: [test]
  classes:
    1: pedestrian
  distractors:
    2: person_on_vehicle
    6: non_mot_vehicle
    7: static_person
    8: distractor
    12: reflection

evaluation:
  classes:
    - name: pedestrian
      dataset_id: 1
      detector_id: 0
      detector_name: person
  ignore_dataset_ids: [2, 6, 7, 8, 12]

download:
  dataset:
    train: "hf://Lekim89/MOT20/train"
    test: "hf://Lekim89/MOT20/test"
    ablation: "hf://Lekim89/MOT20/ablation"
  runs: ""

detector:
  id: yolox_x_mot20_ablation
  model: "models/yolox_x_MOT20_ablation.pt"
  url: "https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_MOT20_ablation.pt"
  imgsz: [800, 1440]
  conf: 0.01
  classes:
    0: person
  by_split:
    ablation:
      id: yolox_x_mot20_ablation
      model: "models/yolox_x_MOT20_ablation.pt"
      url: "https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_MOT20_ablation.pt"

reid:
  id: lmbn_n_duke
  model: "models/lmbn_n_duke.pt"
  url: "https://github.com/mikel-brostrom/boxmot/releases/download/v21.0.0/lmbn_n_duke.pt"
  device: ""
  half: true
  preprocess: resize
  by_split:
    ablation:
      id: lmbn_n_duke
      model: "models/lmbn_n_duke.pt"
      url: "https://github.com/mikel-brostrom/boxmot/releases/download/v21.0.0/lmbn_n_duke.pt"
