id: visdrone

dataset:
  id: visdrone
  root: "boxmot/datasets/mot/VisDrone2019-MOT-test-dev"
  layout: visdrone
  box_type: aabb
  splits:
    val: "sequences"
  default_split: val
  classes:
    1: pedestrian
    2: people
    3: bicycle
    4: car
    5: van
    6: truck
    7: tricycle
    8: awning-tricycle
    9: bus
    10: motor
  distractors:
    0: ignored regions
    11: others

evaluation:
  classes:
    - name: pedestrian
      dataset_id: 1
      detector_id: 0
      detector_name: pedestrian
    - name: people
      dataset_id: 2
      detector_id: 1
      detector_name: people
    - name: bicycle
      dataset_id: 3
      detector_id: 2
      detector_name: bicycle
    - name: car
      dataset_id: 4
      detector_id: 3
      detector_name: car
    - name: van
      dataset_id: 5
      detector_id: 4
      detector_name: van
    - name: truck
      dataset_id: 6
      detector_id: 5
      detector_name: truck
    - name: tricycle
      dataset_id: 7
      detector_id: 6
      detector_name: tricycle
    - name: awning-tricycle
      dataset_id: 8
      detector_id: 7
      detector_name: awning-tricycle
    - name: bus
      dataset_id: 9
      detector_id: 8
      detector_name: bus
    - name: motor
      dataset_id: 10
      detector_id: 9
      detector_name: motor
  ignore_dataset_ids: [0, 11]

download:
  dataset: "https://drive.google.com/uc?export=download&id=14z8Acxopj1d86-qhsF1NwS4Bv3KYa4Wu"
  runs: ""

detector:
  id: yolox_x_visdrone
  model: "models/yolox_x_visdrone.pt"
  url: "https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_visdrone.pt"
  imgsz: [896, 1600]
  conf: 0.01
  classes:
    0: pedestrian
    1: people
    2: bicycle
    3: car
    4: van
    5: truck
    6: tricycle
    7: awning-tricycle
    8: bus
    9: motor

reid:
  id: lmbn_n_duke
  model: "models/lmbn_n_duke.pt"
  url: "https://github.com/mikel-brostrom/boxmot/releases/download/v21.0.0/lmbn_n_duke.pt"
  device: ""
  half: true
  preprocess: resize
