"""Checkpoint metadata and checkpoint persistence."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import torch.nn as nn

from boxmot.reid.backbones.families.csl_tinyvit.multilevel_suppression import (
    MULTILEVEL_SUPPRESSION_IMPLEMENTATION_VERSION,
)
from boxmot.reid.core.artifacts import MODEL_KWARGS_SCHEMA_VERSION
from boxmot.reid.training.ablation import resolve_csl_tinyvit_ablation
from boxmot.reid.training.losses import (
    CenterLoss,
)
from boxmot.reid.training.provenance import model_pretrained_provenance
from boxmot.reid.training.resume import (
    contract_fingerprint,
    run_fingerprint,
)
from boxmot.reid.training.trainer_components.types import (
    ValMetrics,
)


class _CheckpointingMixin:
    @staticmethod
    def _get_num_classes(model) -> int:
        """Infer num_classes from model's classifier layer."""
        if hasattr(model, "classifier"):
            return model.classifier.out_features
        # Multi-branch models (e.g. CSLTinyViT with BNNeck3 head)
        for name, module in model.named_modules():
            if name.endswith("classifier") and hasattr(module, "out_features"):
                return module.out_features
        return -1

    def _checkpoint_metadata(self, model: nn.Module) -> dict[str, Any]:
        """Return stable model/training metadata shared by all checkpoint types."""
        recipe = self._resolve_training_recipe(model)
        resume_contract = self._resume_contract()
        model_kwargs = self._effective_model_kwargs(model)
        metadata = {
            "model_name": self.model_name,
            "model_family": recipe.family,
            "training_family": recipe.family,
            "training_recipe": recipe.name,
            "is_vit": recipe.family == "transformer",
            "is_transformer": recipe.family == "transformer",
            "dataset": self.dataset_name,
            "epochs": self.epochs,
            "warmup_epochs": self.warmup_epochs,
            "eta_min": self.eta_min,
            "num_classes": self._get_num_classes(model),
            "preprocess": self.preprocess,
            "img_size": list(self.img_size),
            "model_kwargs_schema_version": MODEL_KWARGS_SCHEMA_VERSION,
            "model_kwargs": model_kwargs,
            "pretrained": model_pretrained_provenance(model),
            "pretrained_weights": self.pretrained_weights,
            "loss_type": self.loss_type,
            "classifier_loss": self.classifier_loss,
            "inference_feature": self.inference_feature,
            "timm_model_name": getattr(model, "timm_model_name", None),
            "requested_timm_model_name": self.timm_model_name or None,
            "use_timm_head": getattr(model, "use_timm_head", None),
            "timm_head_mode": self.timm_head_mode,
            "mobilenetv4_last_stride": self.mobilenetv4_last_stride,
            "mobilenetv4_neck_mode": self.mobilenetv4_neck_mode,
            "feature_fusion": self.feature_fusion,
            "pyramid_resize_mode": self.pyramid_resize_mode,
            "spatial_conv_mode": self.spatial_conv_mode,
            "post_fusion_mixer": self.post_fusion_mixer,
            "post_fusion_mixer_reduction": self.post_fusion_mixer_reduction,
            "post_fusion_mixer_kernel": list(self.post_fusion_mixer_kernel),
            "post_fusion_mixer_gamma_init": self.post_fusion_mixer_gamma_init,
            "feat_dim": self.feat_dim,
            "neck_dim": self.neck_dim,
            "drop_path_rate": self.drop_path_rate,
            "attention_window_layout": self.attention_window_layout,
            "attention_bias": self.attention_bias,
            "interpolate_pretrained_attention_bias": self.interpolate_pretrained_attention_bias,
            "attention_mask": self.attention_mask,
            "attention_shift": self.attention_shift,
            "stage3_global": self.stage3_global,
            "stage3_downsample": self.stage3_downsample,
            "stage2_width_merge_after": self.stage2_width_merge_after,
            "stage2_mlp_ratio": self.stage2_mlp_ratio,
            "stage3_mlp_ratio": self.stage3_mlp_ratio,
            "stage2_depth": self.stage2_depth,
            "stage3_depth": self.stage3_depth,
            "width_first_hierarchy": self.width_first_hierarchy,
            "identity_registers": self.identity_registers,
            "identity_register_count": self.identity_register_count,
            "identity_register_dim": self.identity_register_dim,
            "identity_register_num_heads": (self.identity_register_num_heads),
            "identity_register_dropout": self.identity_register_dropout,
            "identity_register_gate_init": (self.identity_register_gate_init),
            "identity_register_diversity_weight": (self.identity_register_diversity_weight),
            "identity_register_diversity_margin": (self.identity_register_diversity_margin),
            "native_branch_widths": self.native_branch_widths,
            "fine_map_dim": self.fine_map_dim,
            "compact_deployment_head": self.compact_deployment_head,
            "hierarchical_branch_attention": self.hierarchical_branch_attention,
            "branch_attention_token_dim": self.branch_attention_token_dim,
            "branch_attention_num_heads": self.branch_attention_num_heads,
            "branch_attention_num_layers": self.branch_attention_num_layers,
            "branch_attention_mlp_ratio": self.branch_attention_mlp_ratio,
            "branch_attention_dropout": self.branch_attention_dropout,
            "branch_set_attention": self.branch_set_attention,
            "branch_set_attention_token_dim": self.branch_set_attention_token_dim,
            "branch_set_attention_num_heads": self.branch_set_attention_num_heads,
            "branch_set_attention_num_layers": self.branch_set_attention_num_layers,
            "branch_set_attention_mlp_ratio": self.branch_set_attention_mlp_ratio,
            "branch_set_attention_dropout": self.branch_set_attention_dropout,
            "multiscale_query_decoder": self.multiscale_query_decoder,
            "query_decoder_dim": self.query_decoder_dim,
            "query_decoder_num_heads": self.query_decoder_num_heads,
            "query_decoder_num_layers": self.query_decoder_num_layers,
            "query_decoder_mlp_ratio": self.query_decoder_mlp_ratio,
            "query_decoder_dropout": self.query_decoder_dropout,
            "hierarchical_late_interaction": self.hierarchical_late_interaction,
            "late_interaction_dim": self.late_interaction_dim,
            "late_interaction_num_heads": self.late_interaction_num_heads,
            "late_interaction_num_layers": self.late_interaction_num_layers,
            "late_interaction_sinkhorn_iters": self.late_interaction_sinkhorn_iters,
            "late_interaction_null_tokens": self.late_interaction_null_tokens,
            "late_interaction_negative_identities": self.late_interaction_negative_identities,
            "late_interaction_rerank_topk": self.late_interaction_rerank_topk,
            "late_interaction_base_score_init": self.late_interaction_base_score_init,
            "late_interaction_loss_weight": self.late_interaction_loss_weight,
            "late_interaction_distill_weight": self.late_interaction_distill_weight,
            "late_interaction_temperature": self.late_interaction_temperature,
            "late_interaction_start_epoch": self.late_interaction_start_epoch,
            "late_interaction_ramp_end_epoch": self.late_interaction_ramp_end_epoch,
            "mcpt_mode": self.mcpt_mode,
            "mcpt_hidden_dim": self.mcpt_hidden_dim,
            "mcpt_max_displacement": self.mcpt_max_displacement,
            "mcpt_start_epoch": self.mcpt_start_epoch,
            "mcpt_ramp_end_epoch": self.mcpt_ramp_end_epoch,
            "jpm": self.jpm,
            "jpm_num_groups": self.jpm_num_groups,
            "jpm_shift": self.jpm_shift,
            "jpm_token_dim": self.jpm_token_dim,
            "jpm_num_heads": self.jpm_num_heads,
            "jpm_mlp_ratio": self.jpm_mlp_ratio,
            "jpm_dropout": self.jpm_dropout,
            "jpm_id_loss_weight": self.jpm_id_loss_weight,
            "jpm_metric_loss_weight": self.jpm_metric_loss_weight,
            "adasp_loss_weight": self.adasp_loss_weight,
            "adasp_temperature": self.adasp_temperature,
            "adasp_scale": self.adasp_scale,
            "coarse_branch_ce_weight": self.coarse_branch_ce_weight,
            "fine_branch_ce_weight": self.fine_branch_ce_weight,
            "part_relation_weight": self.part_relation_weight,
            "part_to_global_weight": self.part_to_global_weight,
            "part_relation_teacher_momentum": self.part_relation_teacher_momentum,
            "part_relation_temperature": self.part_relation_temperature,
            "global_ap_loss_weight": self.global_ap_loss_weight,
            "global_ap_temperature": self.global_ap_temperature,
            "global_ap_topk": self.global_ap_topk,
            "global_ap_memory_size": self.global_ap_memory_size,
            "global_ap_momentum": self.global_ap_momentum,
            "global_ap_max_age": self.global_ap_max_age,
            "global_ap_start_epoch": self.global_ap_start_epoch,
            "global_ap_ramp_end_epoch": self.global_ap_ramp_end_epoch,
            "global_ap_decay_start_epoch": self.global_ap_decay_start_epoch,
            "global_ap_decay_end_epoch": self.global_ap_decay_end_epoch,
            "hpgrd_cache_dir": self.hpgrd_cache_dir,
            "hpgrd_manifest_sha256": self._hpgrd_manifest_sha256,
            "hpgrd_part_names": list(getattr(self._privileged_graph_cache, "part_names", ())),
            "retrieval_dataset_sha256": self._retrieval_dataset_sha256,
            "hpgrd_global_weight": self.hpgrd_global_weight,
            "hpgrd_part_weight": self.hpgrd_part_weight,
            "hpgrd_background_weight": self.hpgrd_background_weight,
            "hpgrd_part_drop_weight": self.hpgrd_part_drop_weight,
            "hpgrd_part_drop_probability": self.hpgrd_part_drop_probability,
            "hpgrd_gradient_fraction": self.hpgrd_gradient_fraction,
            "hpgrd_min_confidence": self.hpgrd_min_confidence,
            "compact_metric_loss_weight": self.compact_metric_loss_weight,
            "compact_cosine_distill_weight": self.compact_cosine_distill_weight,
            "compact_pairwise_distill_weight": self.compact_pairwise_distill_weight,
            "vit_lr_profile": self.vit_lr_profile,
            "optimizer_name": recipe.optimizer_name,
            "grad_clip": recipe.grad_clip,
            "backbone_lr_mult": self.backbone_lr_mult,
            "backbone_freeze_epochs": self.backbone_freeze_epochs,
            "gradual_unfreeze": self.gradual_unfreeze,
            "gradual_unfreeze_head_epochs": self.gradual_unfreeze_head_epochs,
            "gradual_unfreeze_stage_epochs": self.gradual_unfreeze_stage_epochs,
            "gradual_unfreeze_backbone_lr_mult": self.gradual_unfreeze_backbone_lr_mult,
            "gradual_unfreeze_backbone_lr_epochs": self.gradual_unfreeze_backbone_lr_epochs,
            "reid_adapter_stages": list(self.reid_adapter_stages),
            "reid_adapter_reduction": self.reid_adapter_reduction,
            "reid_adapter_suppression_tau": self.reid_adapter_suppression_tau,
            "head_pool": self.head_pool,
            "head_parts": list(self.head_parts),
            "head_type": self.head_type,
            "multiscale_channel_alpha": (self.multiscale_channel_alpha),
            "body_slot_mode": self.body_slot_mode,
            "body_slot_alpha": self.body_slot_alpha,
            "body_slot_visibility_floor": (self.body_slot_visibility_floor),
            "part_pooling": self.part_pooling,
            "num_part_tokens": self.num_part_tokens,
            "evidence_num_roles": self.evidence_num_roles,
            "decouple_patterns": self.decouple_patterns,
            "pattern_adapter_dim": self.pattern_adapter_dim,
            "stripe_visibility": self.stripe_visibility,
            "drop_global_aux": self.drop_global_aux,
            "drop_global_aux_ratio": self.drop_global_aux_ratio,
            "branch_aware_metric": self.branch_aware_metric,
            "branch_metric_part_weight": self.branch_metric_part_weight,
            "scale_balanced_branches": self.scale_balanced_branches,
            "multilevel_suppression": self.multilevel_suppression,
            "multilevel_suppression_ratio": self.multilevel_suppression_ratio,
            "multilevel_suppression_loss_weight": (self.multilevel_suppression_loss_weight),
            "multilevel_suppression_start_epoch": (self.multilevel_suppression_start_epoch),
            "multilevel_suppression_ramp_end_epoch": (self.multilevel_suppression_ramp_end_epoch),
            "multilevel_suppression_decay_start_epoch": (self.multilevel_suppression_decay_start_epoch),
            "multilevel_suppression_decay_end_epoch": (self.multilevel_suppression_decay_end_epoch),
            "evidence_alignment_loss_weight": self.evidence_alignment_loss_weight,
            "evidence_alignment_margin": self.evidence_alignment_margin,
            "evidence_sinkhorn_iters": self.evidence_sinkhorn_iters,
            "evidence_sinkhorn_temperature": self.evidence_sinkhorn_temperature,
            "evidence_rerank_topk": self.evidence_rerank_topk,
            "evidence_null_loss_weight": self.evidence_null_loss_weight,
            "evidence_diversity_loss_weight": self.evidence_diversity_loss_weight,
            "anatomical_auxiliary": self.anatomical_auxiliary,
            "anatomical_metadata_dir": self.anatomical_metadata_dir,
            "anatomical_person_mask_dir": self.anatomical_person_mask_dir,
            "anatomical_metadata_provenance": (self._anatomical_metadata_provenance()),
            "anatomical_min_keypoint_confidence": (self.anatomical_min_keypoint_confidence),
            "anatomical_token_dim": self.anatomical_token_dim,
            "anatomical_distill_weight": self.anatomical_distill_weight,
            "anatomical_attention_weight": self.anatomical_attention_weight,
            "anatomical_foreground_weight": self.anatomical_foreground_weight,
            "anatomical_semantic_part_weight": (self.anatomical_semantic_part_weight),
            "anatomical_visibility_weight": self.anatomical_visibility_weight,
            "anatomical_contrastive_weight": (self.anatomical_contrastive_weight),
            "anatomical_descriptor_distill_weight": (self.anatomical_descriptor_distill_weight),
            "anatomical_branch_distill_weight": (self.anatomical_branch_distill_weight),
            "anatomical_branch_global_coefficient": (self.anatomical_branch_global_coefficient),
            "anatomical_branch_coarse_coefficient": (self.anatomical_branch_coarse_coefficient),
            "anatomical_branch_fine_coefficient": (self.anatomical_branch_fine_coefficient),
            "anatomical_pose_teacher_weight": (self.anatomical_pose_teacher_weight),
            "anatomical_query_distill_weight": (self.anatomical_query_distill_weight),
            "anatomical_query_relational_distill_weight": (self.anatomical_query_relational_distill_weight),
            "clean_student_consistency_weight": (self.clean_student_consistency_weight),
            "anatomical_query_diversity_weight": (self.anatomical_query_diversity_weight),
            "anatomical_query_diversity_margin": (self.anatomical_query_diversity_margin),
            "anatomical_part_triplet_weight": (self.anatomical_part_triplet_weight),
            "anatomical_target_type": self.anatomical_target_type,
            "anatomical_teacher_momentum": self.anatomical_teacher_momentum,
            "anatomical_multiscale": self.anatomical_multiscale,
            "anatomical_accessory_query": self.anatomical_accessory_query,
            "anatomical_deployment": self.anatomical_deployment,
            "anatomical_deployment_dim": self.anatomical_deployment_dim,
            "anatomical_deployment_alpha": (self.anatomical_deployment_alpha),
            "anatomical_deployment_id_weight": (self.anatomical_deployment_id_weight),
            "anatomical_deployment_metric_weight": (self.anatomical_deployment_metric_weight),
            "anatomical_local_scale_weight": (self.anatomical_local_scale_weight),
            "anatomical_fine_scale_weight": (self.anatomical_fine_scale_weight),
            "anatomical_cross_scale_weight": (self.anatomical_cross_scale_weight),
            "anatomical_pose_only_reliability": (self.anatomical_pose_only_reliability),
            "anatomical_min_effective_coverage": (self.anatomical_min_effective_coverage),
            "anatomical_student_start_epoch": (self.anatomical_student_start_epoch),
            "anatomical_student_ramp_end_epoch": (self.anatomical_student_ramp_end_epoch),
            "anatomical_query_start_epoch": self.anatomical_query_start_epoch,
            "anatomical_query_ramp_end_epoch": (self.anatomical_query_ramp_end_epoch),
            "anatomical_fine_start_epoch": self.anatomical_fine_start_epoch,
            "anatomical_fine_ramp_end_epoch": self.anatomical_fine_ramp_end_epoch,
            "anatomical_decay_start_epoch": (self.anatomical_decay_start_epoch),
            "anatomical_decay_end_epoch": (self.anatomical_decay_end_epoch),
            "anatomical_temperature": self.anatomical_temperature,
            "head_warmup_epochs": self.head_warmup_epochs,
            "head_warmup_lr_mult": self.head_warmup_lr_mult,
            "early_id_loss_weight": self.early_id_loss_weight,
            "early_id_loss_epochs": self.early_id_loss_epochs,
            "center_loss_ramp_start_epoch": self.center_loss_ramp_start_epoch,
            "center_loss_ramp_end_epoch": self.center_loss_ramp_end_epoch,
            "aux_ce_weight": self.aux_ce_weight,
            "aux_ce_drop_epoch": self.aux_ce_drop_epoch,
            "seed": self.seed,
            "deterministic": self.deterministic,
            "resume_contract": resume_contract,
            "resume_fingerprint": contract_fingerprint(resume_contract),
            "run_fingerprint": run_fingerprint(resume_contract, self.epochs),
        }
        if self.multilevel_suppression:
            metadata["multilevel_suppression_version"] = MULTILEVEL_SUPPRESSION_IMPLEMENTATION_VERSION
        metadata["model"] = {
            "family": recipe.family,
            "training_family": recipe.family,
            "training_recipe": recipe.name,
            "is_vit": recipe.family == "transformer",
            "is_transformer": recipe.family == "transformer",
            "feature_fusion": self.feature_fusion,
            "pyramid_resize_mode": self.pyramid_resize_mode,
            "spatial_conv_mode": self.spatial_conv_mode,
            "timm_model_name": getattr(model, "timm_model_name", None),
            "requested_timm_model_name": self.timm_model_name or None,
            "timm_head_mode": self.timm_head_mode,
            "mobilenetv4_last_stride": self.mobilenetv4_last_stride,
            "mobilenetv4_neck_mode": self.mobilenetv4_neck_mode,
            "pretrained": metadata["pretrained"],
        }
        if self.model_name.startswith(("csl_tinyvit", "mobilenetv4")):
            metadata["model"]["ablation"] = resolve_csl_tinyvit_ablation(self).to_dict()
        reproduction_contract = getattr(model, "reproduction_contract", None)
        if reproduction_contract is not None:
            metadata["model"]["reproduction_contract"] = reproduction_contract
        if recipe.family == "transformer":
            metadata["model"]["transformer"] = {
                "drop_path_rate": self._max_drop_path(model),
                "attention": {
                    "window_layout": self.attention_window_layout,
                    "bias": self.attention_bias,
                    "interpolate_pretrained_bias": self.interpolate_pretrained_attention_bias,
                    "mask": self.attention_mask,
                    "shift": self.attention_shift,
                    "stage3_global": self.stage3_global,
                },
                "speed": {
                    "stage3_downsample": self.stage3_downsample,
                    "stage2_width_merge_after": self.stage2_width_merge_after,
                    "stage2_mlp_ratio": self.stage2_mlp_ratio,
                    "stage3_mlp_ratio": self.stage3_mlp_ratio,
                    "stage2_depth": self.stage2_depth,
                    "stage3_depth": self.stage3_depth,
                    "native_branch_widths": self.native_branch_widths,
                    "fine_map_dim": self.fine_map_dim,
                },
                "hierarchy": {
                    "width_first": self.width_first_hierarchy,
                },
                "identity_registers": {
                    "enabled": self.identity_registers,
                    "count": self.identity_register_count,
                    "dim": self.identity_register_dim,
                    "num_heads": self.identity_register_num_heads,
                    "dropout": self.identity_register_dropout,
                    "gate_init": self.identity_register_gate_init,
                    "diversity_weight": (self.identity_register_diversity_weight),
                    "diversity_margin": (self.identity_register_diversity_margin),
                },
                "deployment": {
                    "compact_head": self.compact_deployment_head,
                    "descriptor_dim": self.feat_dim if self.compact_deployment_head else None,
                },
                "hierarchical_attention": {
                    "enabled": self.hierarchical_branch_attention,
                    "token_dim": self.branch_attention_token_dim,
                    "num_heads": self.branch_attention_num_heads,
                    "num_layers": self.branch_attention_num_layers,
                    "mlp_ratio": self.branch_attention_mlp_ratio,
                    "dropout": self.branch_attention_dropout,
                    "mask": "1_to_2_to_4_tree",
                    "output_init": "zero",
                },
                "branch_set_attention": {
                    "enabled": self.branch_set_attention,
                    "token_dim": self.branch_set_attention_token_dim,
                    "num_heads": self.branch_set_attention_num_heads,
                    "num_layers": self.branch_set_attention_num_layers,
                    "mlp_ratio": self.branch_set_attention_mlp_ratio,
                    "dropout": self.branch_set_attention_dropout,
                    "mask": "none",
                    "output_init": "zero",
                    "input_location": "post_pool_pre_reduction",
                },
                "multiscale_query_decoder": {
                    "enabled": self.multiscale_query_decoder,
                    "token_dim": self.query_decoder_dim,
                    "num_heads": self.query_decoder_num_heads,
                    "num_layers": self.query_decoder_num_layers,
                    "mlp_ratio": self.query_decoder_mlp_ratio,
                    "dropout": self.query_decoder_dropout,
                    "query_seeds": "existing_7_pooled_outputs",
                    "memory": "final_stage2_stage0_maps",
                    "position_encoding": "2d_sine_cosine",
                    "attention_masks": "none",
                    "memory_projection": "shared",
                    "output_init": "zero",
                },
                "hierarchical_late_interaction": {
                    "enabled": self.hierarchical_late_interaction,
                    "token_dim": self.late_interaction_dim,
                    "num_heads": self.late_interaction_num_heads,
                    "num_layers": self.late_interaction_num_layers,
                    "sinkhorn_iters": self.late_interaction_sinkhorn_iters,
                    "null_tokens": self.late_interaction_null_tokens,
                    "base_score_init": self.late_interaction_base_score_init,
                    "rerank_topk": self.late_interaction_rerank_topk,
                },
                "mcpt": {
                    "mode": self.mcpt_mode,
                    "hidden_dim": self.mcpt_hidden_dim,
                    "max_displacement": self.mcpt_max_displacement,
                    "start_epoch": self.mcpt_start_epoch,
                    "ramp_end_epoch": self.mcpt_ramp_end_epoch,
                },
                "jpm": {
                    "enabled": self.jpm,
                    "num_groups": self.jpm_num_groups,
                    "shift": self.jpm_shift,
                    "token_dim": self.jpm_token_dim,
                    "num_heads": self.jpm_num_heads,
                    "mlp_ratio": self.jpm_mlp_ratio,
                    "dropout": self.jpm_dropout,
                    "deployment": "training_only",
                },
                "multilevel_suppression": {
                    "enabled": self.multilevel_suppression,
                    "ratio": self.multilevel_suppression_ratio,
                    **(
                        {"version": (MULTILEVEL_SUPPRESSION_IMPLEMENTATION_VERSION)}
                        if self.multilevel_suppression
                        else {}
                    ),
                    "loss_weight": self.multilevel_suppression_loss_weight,
                    "start_epoch": self.multilevel_suppression_start_epoch,
                    "ramp_end_epoch": (self.multilevel_suppression_ramp_end_epoch),
                    "decay_start_epoch": (self.multilevel_suppression_decay_start_epoch),
                    "decay_end_epoch": (self.multilevel_suppression_decay_end_epoch),
                    "deployment": "training_only",
                },
                "reid_adapters": {
                    "stages": list(self.reid_adapter_stages),
                    "reduction": self.reid_adapter_reduction,
                    "suppression_tau": self.reid_adapter_suppression_tau,
                },
                "lr_profile": self.vit_lr_profile,
            }
        else:
            metadata["model"][recipe.family] = {
                "timm_model_name": getattr(model, "timm_model_name", None),
                "use_timm_head": getattr(model, "use_timm_head", None),
                "timm_head_mode": getattr(model, "timm_head_mode", None),
                "mobilenetv4_last_stride": getattr(
                    model,
                    "mobilenetv4_last_stride",
                    None,
                ),
                "mobilenetv4_neck_mode": getattr(
                    model,
                    "mobilenetv4_neck_mode",
                    None,
                ),
                "feature_fusion": self.feature_fusion,
                "drop_path_rate": self._max_drop_path(model),
            }
        metadata["optimization"] = {
            "recipe": recipe.name,
            "optimizer": recipe.optimizer_name,
            "lr": self.lr,
            "weight_decay": self.weight_decay,
            "warmup_epochs": self.warmup_epochs,
            "grad_clip": recipe.grad_clip,
            "layer_decay": recipe.layer_decay(self),
            "mcpt_lr_multiplier": self.mcpt_lr_multiplier,
            "backbone_lr_mult": self.backbone_lr_mult,
        }
        if self.data_specs:
            metadata["data_specs"] = [dict(spec) for spec in self.data_specs]
        return metadata

    def _save_checkpoint(
        self,
        model,
        path: Path,
        epoch: int,
        val: Optional[ValMetrics],
        optimizer=None,
        optimizer_center=None,
        criterion_center: Optional[CenterLoss] = None,
        criterion_classifier: Optional[nn.Module] = None,
        ema_model=None,
        scheduler=None,
        best_mAP: float = 0.0,
    ):
        self.checkpoint_manager.save(
            path,
            model=model,
            epoch=epoch,
            val=val,
            optimizer=optimizer,
            optimizer_center=optimizer_center,
            criterion_center=criterion_center,
            criterion_classifier=criterion_classifier,
            ema_model=ema_model,
            scheduler=scheduler,
            grad_scaler=getattr(self, "_scaler", None),
            training_state=(self._training_auxiliary_state() if optimizer is not None else None),
            best_mAP=best_mAP,
            resumable=optimizer is not None,
        )
