# SportsMOT validation tuning, previously used as the global defaults.
tracker: hybridsort
max_age: 230
max_obs: 90
min_hits: 1
iou_threshold: 0.24623615333496582
asso_func: diou
cmc_method: ecc
use_embeddings: true
low_thresh: 0.1
delta_t: 4
inertia: 0.07385224556640951
use_byte: false
longterm_bank_length: 270
alpha: 0.9189916764734039
adapfs: true
track_thresh: 0.3190991353484191
eg_weight_high_score: 3.8961609177336562
eg_weight_low_score: 0.5096125821683565
tcm_first_step: true
tcm_byte_step: true
tcm_byte_step_weight: 1.0
with_longterm_reid: true
longterm_reid_weight: 1.9752492019041523
with_longterm_reid_correction: true
longterm_reid_correction_thresh: 0.11310432273756706
longterm_reid_correction_thresh_low: 0.3479740001301599
det_thresh: 0.38633684113126876
