common:
  imgsz:
  fps: 30
  conf:
  iou: 0.7
  device: ""
  batch_size: 16
  auto_batch: true
  resume: true
  n_threads:
  project: runs
  name: ""
  exist_ok: true
  half: false
  vid_stride: 1
  ci: false
  tracker: bytetrack
  verbose: false
  agnostic_nms: false
  postprocessing: none
  show: false
  show_labels: true
  show_conf: true
  show_trajectories: false
  show_kf_preds: false
  save_txt: false
  save_crop: false
  save: false
  line_width:
  per_class: false
  target_id:
  classes:

modes:
  track:
    source: "0"
    benchmark: ""
    split: ""
  generate:
    data:
    source:
    benchmark: ""
    split: ""
  eval:
    data:
    source:
    benchmark: ""
    split: ""
  tune:
    data:
    source:
    benchmark: ""
    split: ""
    n_trials: 4
    objectives: [HOTA, MOTA, IDF1]
    maximize: [HOTA, MOTA, IDF1]
    minimize: []
  export:
    batch_size: 1
    imgsz: 640
    device: cpu
    optimize: false
    dynamic: false
    simplify: false
    opset: 18
    workspace: 4
    weights:
    include: [torchscript]
