name: Bug
# title: " "
description: Report a Yolo Tracking bug
labels: [bug]
body:

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.
          required: true

  - type: dropdown
    attributes:
      label: Yolv8 Tracking Component
      description: |
        Please select the part of Yolo Tracking where you found the bug.
      multiple: true
      options:
        - "Tracking"
        - "Evaluation"
        - "Evolution"
        - "Integrations"
        - "Other"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the environment information you used to produce the bug.
      placeholder: |
        - Yolo Tracking v10.0.13 🚀 Python-3.8.16 torch-1.13.1+cu117 CUDA:0 (Quadro P2000, 4032MiB)
        - ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to [**reproduce**](https://stackoverflow.com/help/minimal-reproducible-example) the problem.
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: true

