name: Bug Report
# title: " "
description: Report a Yolov5_StrongSORT_OSNet bug
labels: [bug]
body:

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.
          required: true

  - type: dropdown
    attributes:
      label: Yolov5_StrongSORT_OSNet Component
      description: |
        Please select the part of Yolov5_StrongSORT_OSNet where you found the bug.
      multiple: true
      options:
        - "Tracking"
        - "Evaluation"
        - "Integrations"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - YOLO: YOLOv5 🚀 v6.0-67-g60e42e1 torch 1.9.0+cu111 CUDA:0 (A100-SXM4-40GB, 40536MiB)
        - StrongSORT: osnet_x0_25
        - OS: Ubuntu 20.04
        - Python: 3.9.0
        - ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

