id: yolox-x-mot17

box_type: aabb

classes:
  0: person

inference:
  image_size: [800, 1440]
  confidence_threshold: 0.01

checkpoints:
  ablation:
    path: models/yolox_x_MOT17_ablation.pt
    uri: https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_MOT17_ablation.pt
  test:
    path: models/yolox_x_MOT17_test.pt
    uri: https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_MOT17_test.pt
