id: yolox_x_mot20_ablation
model: "models/yolox_x_MOT20_ablation.pt"
url: "https://huggingface.co/Lekim89/yolox/resolve/main/yolox_x_MOT20_ablation.pt"
imgsz: [800, 1440]
conf: 0.01
classes:
  0: person
