id: yolo11l_3ch
model: "models/yolo11l_3ch.pt"
url: "https://drive.google.com/uc?id=15gmA4-Yclvh5EZvTJYhcyV1CVdNRGIkR"
box_type: obb
imgsz: [1280, 1280]
conf: 0.2
classes:
  0: car
  1: bike
  2: pedestrian
  3: van
  4: truck
  5: bus
  6: tricycle
  7: awning-bike
