id: yolox

box_type: aabb

classes:
  0: person

inference:
  image_size: [1080, 1920]
  confidence_threshold: 0.01

checkpoints:
  n:
    path: models/yolox_n.pt
    uri: gdrive://1AoN2AxzVwOLM0gJ15bcwqZUpFjlDV1dX
  s:
    path: models/yolox_s.pt
    uri: gdrive://1uSmhXzyV1Zvb4TJJCzpsZOIcw7CCJLxj
  m:
    path: models/yolox_m.pt
    uri: gdrive://11Zb0NN_Uu7JwUd9e6Nk8o2_EUfxWqsun
  l:
    path: models/yolox_l.pt
    uri: gdrive://1XwfUuCBF4IgWBWK2H7oOhQgEj9Mrb3rz
  x:
    path: models/yolox_x.pt
    uri: gdrive://1P4mY0Yyd3PPTybgZkjMYhFri88nTmJX5
