id: yolox_x_dancetrack_ablation
model: "models/yolox_x_dancetrack_ablation.pt"
url: "https://drive.google.com/uc?id=1ZKpYmFYCsRdXuOL60NRuc7VXAFYRskXB"
imgsz: [800, 1440]
conf: 0.01
classes:
  0: person
