id: yolox_x_visdrone
model: "models/yolox_x_visdrone.pt"
url: "https://drive.google.com/uc?id=1ajehBs9enBHhuBqGIoQPGqkkzasE9d3o"
imgsz: [800, 1440]
conf: 0.01
classes:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor
