min_conf:
  type: uniform
  default: 0.1  # from the default parameters
  range: [0.1, 0.3]

track_thresh:
  type: uniform
  default: 0.6  # from the default parameters
  range: [0.4, 0.6]

track_buffer:
  type: randint
  default: 30  # from the default parameters
  range: [10, 61, 10]  # step size of 10, upper bound exclusive

match_thresh:
  type: uniform
  default: 0.9  # from the default parameters
  range: [0.7, 0.9]

frame_rate:
  type: choice
  default: 30  # from the default parameters
  choices: [30]  # static choice for Ray Search