# BoxMOT AGPL-3.0 license

from boxmot.reid.backbones.families.csl_tinyvit.attention import Attention
from boxmot.reid.backbones.families.csl_tinyvit.blocks import (
    BasicLayer,
    BodySlotReadWrite,
    Conv2d_BN,
    ConvLayer,
    DropPath,
    IdentityRegisterCommunication,
    LayerNorm2d,
    MBConv,
    NormPreservingWidthMerge,
    PatchEmbed,
    PatchMerging,
    ReIDResidualAdapter,
    RMSFeatureSuppression,
    TinyViTBlock,
    TinyViTMlp,
)
from boxmot.reid.backbones.families.csl_tinyvit.fusion import (
    CSLTinyViTFeatureFusion,
    PostFusionLocalMixer,
)
from boxmot.reid.backbones.families.csl_tinyvit.heads import (
    BodySlotFeatures,
    BodySlotHead,
    BranchSetAttention,
    GPCLiteMultiBranchHead,
    HierarchicalBranchAttention,
    HierarchicalLateInteractionMatcher,
    LMBNStyleMultiBranchHead,
    MultiBranchHead,
    ResidualMultiScaleQueryDecoder,
)
from boxmot.reid.backbones.families.csl_tinyvit.jigsaw import (
    JigsawPatchAuxiliary,
)
from boxmot.reid.backbones.families.csl_tinyvit.model import CSLTinyViT
from boxmot.reid.backbones.families.csl_tinyvit.pooling import (
    ActivatedGeM,
    DSELitePool,
    GeM,
    LearnedPartTokenPool,
    PatternAdapter,
    SemanticVisibilityPartPool,
    SpatialTopDrop,
    StripeVisibilityGate,
)
from boxmot.reid.backbones.families.csl_tinyvit.transport import (
    MCPT_MODES,
    MCPTDiagnostics,
    MonotonicCanonicalPartTransport,
)
from boxmot.reid.backbones.families.csl_tinyvit.variants import (
    csl_tinyvit_7m,
    csl_tinyvit_7m_lmbn,
    csl_tinyvit_7m_v20,
    csl_tinyvit_11m,
    csl_tinyvit_11m_lmbn,
    csl_tinyvit_11m_v20,
    csl_tinyvit_23m,
    csl_tinyvit_23m_lmbn,
    csl_tinyvit_large,
    csl_tinyvit_lmbn,
    csl_tinyvit_normal,
    csl_tinyvit_small,
)

__all__ = [
    "ActivatedGeM",
    "Attention",
    "BasicLayer",
    "BodySlotFeatures",
    "BodySlotHead",
    "BodySlotReadWrite",
    "BranchSetAttention",
    "CSLTinyViT",
    "CSLTinyViTFeatureFusion",
    "Conv2d_BN",
    "ConvLayer",
    "DSELitePool",
    "DropPath",
    "GPCLiteMultiBranchHead",
    "GeM",
    "HierarchicalBranchAttention",
    "HierarchicalLateInteractionMatcher",
    "IdentityRegisterCommunication",
    "JigsawPatchAuxiliary",
    "LMBNStyleMultiBranchHead",
    "LayerNorm2d",
    "LearnedPartTokenPool",
    "MBConv",
    "MCPTDiagnostics",
    "MCPT_MODES",
    "MultiBranchHead",
    "MonotonicCanonicalPartTransport",
    "NormPreservingWidthMerge",
    "PatchEmbed",
    "PatchMerging",
    "PatternAdapter",
    "PostFusionLocalMixer",
    "ReIDResidualAdapter",
    "RMSFeatureSuppression",
    "ResidualMultiScaleQueryDecoder",
    "SemanticVisibilityPartPool",
    "SpatialTopDrop",
    "StripeVisibilityGate",
    "TinyViTBlock",
    "TinyViTMlp",
    "csl_tinyvit_7m",
    "csl_tinyvit_7m_lmbn",
    "csl_tinyvit_7m_v20",
    "csl_tinyvit_11m",
    "csl_tinyvit_11m_lmbn",
    "csl_tinyvit_11m_v20",
    "csl_tinyvit_23m",
    "csl_tinyvit_23m_lmbn",
    "csl_tinyvit_large",
    "csl_tinyvit_lmbn",
    "csl_tinyvit_normal",
    "csl_tinyvit_small",
]
