track_high_thresh:
  type: uniform
  default: 0.6  # from the default parameters
  range: [0.3, 0.7]

track_low_thresh:
  type: uniform
  default: 0.1  # from the default parameters
  range: [0.1, 0.3]

new_track_thresh:
  type: uniform
  default: 0.7  # from the default parameters
  range: [0.1, 0.8]

track_buffer:
  type: randint
  default: 30  # from the default parameters
  range: [20, 81]

match_thresh:
  type: uniform
  default: 0.8  # from the default parameters
  range: [0.1, 0.9]

use_cmc:
  type: choice
  default: True  # from the default parameters
  options: [False, True]
  activates:
    cmc_method:
      type: choice
      default: ecc  # from the default parameters
      options: [sof, ecc]

frame_rate:
  type: choice
  default: 30  # from the default parameters
  options: [25, 30]

fuse_first_associate:
  type: choice
  default: False  # from the default parameters
  options: [False, True]

with_reid:
  type: choice
  default: True  # from the default parameters
  options: [False, True]
  activates:
    proximity_thresh:
      type: uniform
      default: 0.5  # from the default parameters
      range: [0.25, 0.75]
    appearance_thresh:
      type: uniform
      default: 0.25  # from the default parameters
      range: [0.1, 0.8]
    unconfirmed_emb_scale:
      type: uniform
      default: 2.0  # from the default parameters
      range: [1.0, 4.0]

second_match_thresh:
  type: uniform
  default: 0.5  # from the default parameters
  range: [0.1, 0.9]

unconfirmed_match_thresh:
  type: uniform
  default: 0.7  # from the default parameters
  range: [0.1, 0.9]

removed_stracks_buffer:
  type: randint
  default: 100  # from the default parameters
  range: [50, 501]
