det_thresh:
  type: uniform
  default: 0.38633684113126876
  range: [0.1, 0.8]

max_age:
  type: qrandint
  default: 230
  range: [10, 360, 10]

max_obs:
  type: qrandint
  default: 90
  range: [10, 101, 10]

min_hits:
  type: randint
  default: 1
  range: [1, 6]

iou_threshold:
  type: uniform
  default: 0.24623615333496582
  range: [0.1, 0.7]

asso_func:
  type: choice
  default: diou
  options: [iou, giou, diou, ciou, hmiou, ct_dist]

dataset:
  type: choice
  default: ""
  options: [""]

cmc_method:
  type: choice
  default: ecc
  options: [sof, ecc]

delta_t:
  type: randint
  default: 4
  range: [1, 6]

use_byte:
  type: choice
  default: False
  options: [False, True]
  activates:
    low_thresh:
      type: uniform
      default: 0.1
      range: [0.05, 0.5]
    TCM_byte_step:
      type: choice
      default: True
      options: [False, True]
      activates:
        TCM_byte_step_weight:
          type: uniform
          default: 1.0
          range: [0.5, 2.0]

TCM_first_step:
  type: choice
  default: True
  options: [False, True]
  activates:
    inertia:
      type: uniform
      default: 0.07385224556640951
      range: [0.001, 0.2]

track_thresh:
  type: uniform
  default: 0.3190991353484191
  range: [0.3, 0.9]

with_reid:
  type: choice
  default: True
  options: [False, True]
  activates:
    longterm_bank_length:
      type: qrandint
      default: 270
      range: [10, 360, 10]
    alpha:
      type: uniform
      default: 0.9189916764734039
      range: [0.7, 0.99]
    adapfs:
      type: choice
      default: True
      options: [False, True]
    EG_weight_high_score:
      type: uniform
      default: 3.8961609177336562
      range: [1.5, 8.0]
    EG_weight_low_score:
      type: uniform
      default: 0.5096125821683565
      range: [0.5, 3.0]
    high_score_matching_thresh:
      type: uniform
      default: 0.6764212909416498
      range: [0.5, 0.99]
    with_longterm_reid:
      type: choice
      default: True
      options: [False, True]
      activates:
        longterm_reid_weight:
          type: uniform
          default: 1.9752492019041523
          range: [0.0, 2.0]
    with_longterm_reid_correction:
      type: choice
      default: True
      options: [False, True]
      activates:
        longterm_reid_correction_thresh:
          type: uniform
          default: 0.11310432273756706
          range: [0.1, 0.7]
        longterm_reid_correction_thresh_low:
          type: uniform
          default: 0.3479740001301599
          range: [0.1, 0.7]
