max_age:
  type: randint
  default: 88
  range: [15, 200]

min_hits:
  type: randint
  default: 1
  range: [1, 5]

det_thresh:
  type: uniform
  default: 0.6191281742510143
  range: [0.1, 0.9]

iou_threshold:
  type: uniform
  default: 0.08854815430240996
  range: [0.05, 0.99]

use_cmc:
  type: choice
  default: True
  options: [False, True]
  activates:
    cmc_method:
      type: choice
      default: sof
      options: [sof, ecc]

min_box_area:
  type: randint
  default: 75
  range: [5, 100]

aspect_ratio_thresh:
  type: uniform
  default: 1.7492471866426091
  range: [0.1, 2.0]

lambda_iou:
  type: uniform
  default: 1.7168380902528035
  range: [0.1, 2.0]

lambda_mhd:
  type: uniform
  default: 0.18124834268378442
  range: [0.1, 2.0]

lambda_shape:
  type: uniform
  default: 1.6204253839815765
  range: [0.1, 2.0]

use_dlo_boost:
  type: choice
  default: True
  options: [False, True]
  activates:
    dlo_boost_coef:
      type: uniform
      default: 1.592685421502537
      range: [0.3, 2.0]

use_duo_boost:
  type: choice
  default: False
  options: [False, True]

s_sim_corr:
  type: choice
  default: False
  options: [False, True]

use_rich_s:
  type: choice
  default: False
  options: [False, True]

use_sb:
  type: choice
  default: False
  options: [False, True]

use_vt:
  type: choice
  default: True
  options: [False, True]

with_reid:
  type: choice
  default: True
  options: [False, True]
  activates:
    recovery_appearance_thresh:
      type: uniform
      default: 0.8284819362418853
      range: [0.2, 0.99]
    recovery_iou_thresh:
      type: uniform
      default: 0.253970578980223
      range: [0.0, 0.5]
    recovery_max_age:
      type: randint
      default: 9
      range: [1, 120]
    feat_alpha:
      type: uniform
      default: 0.8474299033397772
      range: [0.7, 1.0]

track_low_thresh:
  type: uniform
  default: 0.050002145016990886
  range: [0.01, 0.3]

use_second_pass:
  type: choice
  default: True
  options: [False, True]
  activates:
    second_iou_thresh:
      type: uniform
      default: 0.784088852127146
      range: [0.3, 0.9]
    second_appearance_thresh:
      type: uniform
      default: 0.5884305667909087
      range: [0.2, 0.9]
    second_pass_max_age:
      type: randint
      default: 2
      range: [1, 10]
    second_pass_min_hits:
      type: randint
      default: 7
      range: [1, 20]

new_track_thresh:
  type: uniform
  default: 0.7006691095625072
  range: [0.3, 0.9]

confirm_hits:
  type: randint
  default: 1
  range: [1, 8]

instant_confirm_thresh:
  type: uniform
  default: 0.8257187606072911
  range: [0.5, 0.95]

tentative_max_age:
  type: randint
  default: 4
  range: [0, 5]

duplicate_iou_thresh:
  type: uniform
  default: 0.9256184820651551
  range: [0.5, 1.0]

ams_enabled:
  type: choice
  default: True
  options: [False, True]
  activates:
    ams_alpha0:
      type: uniform
      default: 0.9383280226652425
      range: [0.0, 1.0]
    ams_threshold:
      type: uniform
      default: 0.8664176316686335
      range: [0.0, 1.0]
    ams_buffer_size:
      type: randint
      default: 34
      range: [3, 60]
    ams_shrink_ratio:
      type: uniform
      default: 0.9080813534161316
      range: [0.5, 1.0]

lambda_emb_multiplier:
  type: uniform
  default: 2.998169378915523
  range: [0.1, 8.0]

gta_enabled:
  type: choice
  default: False
  options: [False, True]
  activates:
    gta_appearance_thresh:
      type: uniform
      default: 0.7125445489563044
      range: [0.3, 0.8]
    gta_min_track_length:
      type: randint
      default: 7
      range: [2, 15]
    gta_smooth_tau:
      type: uniform
      default: 14.757519908748044
      range: [1.0, 20.0]
    gta_interpolate:
      type: choice
      default: False
      options: [False, True]
    gta_max_gap:
      type: randint
      default: 40
      range: [15, 150]

adaptive_kf:
  type: choice
  default: False
  options: [False, True]