"""Generate the Python module reference consumed by MkDocs.

The module tree and module docstrings are parsed statically so documentation
builds never import optional backends or execute package-level side effects.
Mkdocstrings remains responsible for parsing and rendering object docstrings
from the generated pages.
"""

from __future__ import annotations

import ast
import logging
import tokenize
from dataclasses import dataclass
from pathlib import Path

LOGGER = logging.getLogger("mkdocs.plugins.boxmot_api_reference")

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = REPO_ROOT / "boxmot"
REFERENCE_ROOT = Path("reference")
GENERATED_NOTICE = "<!-- Generated by docs/gen_ref_pages.py; do not edit. -->"


@dataclass(frozen=True)
class ModuleReference:
    """Source and output metadata for one Python module."""

    source_path: Path
    identifier: str
    page_path: Path
    nav_parts: tuple[str, ...]
    docstring: str | None
    local_members: tuple[str, ...]

    @property
    def is_package(self) -> bool:
        """Return whether this reference represents a package initializer."""

        return self.source_path.name == "__init__.py"


def _parse_module(source_path: Path) -> ast.Module:
    """Parse a Python module without importing or executing it."""

    try:
        with tokenize.open(source_path) as source_file:
            source = source_file.read()
        return ast.parse(source, filename=str(source_path))
    except (OSError, SyntaxError, UnicodeError) as exc:
        raise ValueError(f"Unable to parse Python module {source_path}: {exc}") from exc


def parse_module_docstring(source_path: Path) -> str | None:
    """Return a module docstring without importing or executing the module."""

    return ast.get_docstring(_parse_module(source_path), clean=True)


def _assigned_names(target: ast.expr) -> tuple[str, ...]:
    """Return simple names introduced by an assignment target."""

    if isinstance(target, ast.Name):
        return (target.id,)
    if isinstance(target, (ast.List, ast.Tuple)):
        return tuple(name for element in target.elts for name in _assigned_names(element))
    return ()


def _local_public_members(module: ast.Module) -> tuple[str, ...]:
    """Return public members defined by a module, excluding imported re-exports."""

    names: list[str] = []
    for node in module.body:
        if isinstance(node, (ast.AsyncFunctionDef, ast.ClassDef, ast.FunctionDef)):
            names.append(node.name)
        elif isinstance(node, ast.Assign):
            names.extend(name for target in node.targets for name in _assigned_names(target))
        elif isinstance(node, ast.AnnAssign):
            names.extend(_assigned_names(node.target))

    return tuple(dict.fromkeys(name for name in names if not name.startswith("_")))


def discover_modules(
    package_root: Path = PACKAGE_ROOT,
    reference_root: Path = REFERENCE_ROOT,
) -> tuple[ModuleReference, ...]:
    """Discover documentable modules in deterministic package order."""

    package_root = package_root.resolve()
    if not package_root.is_dir():
        raise ValueError(f"Python package directory does not exist: {package_root}")

    source_root = package_root.parent
    references: list[ModuleReference] = []
    identifiers: dict[str, Path] = {}
    page_paths: dict[Path, Path] = {}
    for source_path in sorted(package_root.rglob("*.py")):
        if source_path.name == "__main__.py" or "__pycache__" in source_path.parts:
            continue

        module_path = source_path.relative_to(source_root).with_suffix("")
        module_parts = module_path.parts
        is_package = module_parts[-1] == "__init__"
        if is_package:
            module_parts = module_parts[:-1]
            page_path = reference_root.joinpath(*module_parts, "index.md")
        else:
            page_path = reference_root.joinpath(*module_parts).with_suffix(".md")

        identifier = ".".join(module_parts)
        if previous_source := identifiers.get(identifier):
            raise ValueError(f"Modules {previous_source} and {source_path} have the same identifier: {identifier}")
        if previous_source := page_paths.get(page_path):
            raise ValueError(f"Modules {previous_source} and {source_path} map to the same reference page: {page_path}")

        module = _parse_module(source_path)
        identifiers[identifier] = source_path
        page_paths[page_path] = source_path
        references.append(
            ModuleReference(
                source_path=source_path,
                identifier=identifier,
                page_path=page_path,
                nav_parts=tuple(module_parts),
                docstring=ast.get_docstring(module, clean=True),
                local_members=_local_public_members(module),
            )
        )

    return tuple(references)


def render_module_page(reference: ModuleReference) -> str:
    """Render one module page for mkdocstrings to populate."""

    lines = [
        "---",
        "search:",
        "  boost: 0.5",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        f"::: {reference.identifier}",
        "    options:",
        "      heading_level: 1",
        "      show_if_no_docstring: true",
        "      show_root_full_path: true",
        "      show_root_heading: true",
        "      show_source: false",
        "      show_symbol_type_heading: true",
        "      show_symbol_type_toc: true",
    ]
    if reference.local_members:
        lines.append("      members:")
        lines.extend(f"        - {member}" for member in reference.local_members)
    else:
        lines.append("      members: false")
    return "\n".join(lines) + "\n"


def render_reference_index(references: tuple[ModuleReference, ...]) -> str:
    """Render the landing page for the generated code reference."""

    return (
        f"{GENERATED_NOTICE}\n\n"
        "# Code reference\n\n"
        "This reference covers the `boxmot` library modules, including internal "
        "implementation modules, and mirrors their package hierarchy. Executable "
        "`__main__` entry-point shims are omitted. Pages are assembled from Python "
        "source at build time and rendered from signatures and docstrings by "
        "mkdocstrings.\n\n"
        f"The current source tree contains {len(references)} module reference pages.\n"
    )


def generate_reference(
    package_root: Path = PACKAGE_ROOT,
    reference_root: Path = REFERENCE_ROOT,
    repo_root: Path = REPO_ROOT,
) -> None:
    """Write virtual API pages and their literate navigation for MkDocs."""

    import mkdocs_gen_files
    from mkdocs.structure.files import InclusionLevel

    references = discover_modules(package_root, reference_root)
    nav = mkdocs_gen_files.Nav()
    nav["Overview"] = "index.md"

    index_path = reference_root / "index.md"
    with mkdocs_gen_files.open(index_path, "w") as index_file:
        index_file.write(render_reference_index(references))
    mkdocs_gen_files.set_edit_path(index_path, Path("gen_ref_pages.py"))

    for reference in references:
        relative_page_path = reference.page_path.relative_to(reference_root)
        nav[reference.nav_parts] = relative_page_path.as_posix()
        with mkdocs_gen_files.open(reference.page_path, "w") as page_file:
            page_file.write(render_module_page(reference))

        source_path = reference.source_path.relative_to(repo_root)
        mkdocs_gen_files.set_edit_path(reference.page_path, Path("..") / source_path)

    nav_path = reference_root / "SUMMARY.md"
    with mkdocs_gen_files.open(nav_path, "w") as nav_file:
        nav_file.writelines(nav.build_literate_nav())
    generated_nav = mkdocs_gen_files.files.get_file_from_path(nav_path.as_posix())
    if generated_nav is None:
        raise RuntimeError(f"Generated navigation file is unavailable: {nav_path}")
    generated_nav.inclusion = InclusionLevel.EXCLUDED

    undocumented = sum(reference.docstring is None for reference in references)
    LOGGER.info(
        "Generated API reference pages for %d BoxMOT modules (%d without module docstrings)",
        len(references),
        undocumented,
    )


# mkdocs-gen-files executes configured scripts with runpy.run_path.
if __name__ == "<run_path>":
    generate_reference()
elif __name__ == "__main__":
    raise SystemExit("Run this build-time generator with `mkdocs build`.")
