id: dancetrack-ablation

path: "boxmot/engine/trackeval/data/test1"
split: "val"
train:
val: "val"
test:

layout: mot
box_type: aabb

detector: yolox_x_dancetrack_ablation
reid: lmbn_n_duke

names:
  1: pedestrian

distractors: {}
class_map: {}

download:
  dataset: "https://huggingface.co/datasets/noahcao/dancetrack/resolve/main/test1.zip"
