id: dancetrack

root: "boxmot/engine/eval/trackeval/data/test1"
layout: mot
box_type: aabb

splits:
  val: "val"
default_split: val

classes:
  1: pedestrian

defaults:
  detector: yolox_x_dancetrack
  reid: lmbn_n_duke

download:
  dataset: "https://huggingface.co/datasets/noahcao/dancetrack/resolve/main/test1.zip"
