id: dancetrack

format:
  layout: mot
  box_type: aabb

storage:
  root: boxmot/datasets/mot/test1

default_split: val

splits:
  val:
    path: val
    has_ground_truth: true

classes:
  target:
    pedestrian: 1

resources:
  dataset:
    type: archive
    uri: https://huggingface.co/datasets/noahcao/dancetrack/resolve/main/test1.zip
