id: dota8-mot

path: "assets/DOTA8-MOT"
split: "train"
train: "train"
val:
test:

layout: mmot_rgb
box_type: obb
trackeval: mmot_rgb

names:
  1: plane
  5: tennis court
  11: small vehicle
  15: swimming pool

distractors: {}
class_map: {}

models: dota8-mot-models

download:
  runs: ""
  dataset: ""
