id: dota8-mot

path: "assets/DOTA8-MOT"
split: "train"
train: "train"
val:
test:

layout: mot
box_type: obb

detector: yolo11s_obb
reid: lmbn_n_duke

names:
  1: plane
  5: tennis court
  11: small vehicle
  15: swimming pool

distractors: {}
class_map: {}
