id: mmot-obb

path: "boxmot/engine/trackeval/data/MMOT-OBB"
split: "train"
train: "train"
val:
test:

layout: mmot_rgb
box_type: obb
trackeval: mmot_rgb

names:
  1: car
  2: bike
  3: pedestrian
  4: van
  5: truck
  6: bus
  7: tricycle
  8: awning-bike

distractors: {}
class_map: {}

models: mmot-obb-models

download:
  runs: ""
  dataset: "https://github.com/mikel-brostrom/boxmot/releases/download/v16.0.11/MMOT-OBB.zip"
