id: mmot-obb

root: "boxmot/engine/eval/trackeval/data/MMOT-OBB"
layout: mot
box_type: obb

splits:
  train: "train/npy"
  test: "test/npy"
default_split: train

classes:
  1: car
  2: bike
  3: pedestrian
  4: van
  5: truck
  6: bus
  7: tricycle
  8: awning-bike

defaults:
  detector: yolo11l_3ch
  reid: lmbn_n_duke

download:
  dataset: "https://github.com/mikel-brostrom/boxmot/releases/download/v16.0.11/MMOT-OBB.zip"
