id: mot17-seg

path: "boxmot/engine/trackeval/data/MOT17-ablation"
split: "train"
train: "train"
val:
test:

layout: mot
box_type: aabb

detector: yolo26x-seg
reid: lmbn_n_duke

names:
  1: pedestrian

distractors:
  2: person_on_vehicle
  7: static_person
  8: distractor
  12: reflection

class_map: {}

download:
  dataset: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/MOT17-ablation.zip"
  runs: ""
