id: mot17-mini

root: "assets/MOT17-mini"
layout: mot
box_type: aabb

splits:
  train: "train"
default_split: train

classes:
  1: pedestrian

distractors:
  2: person_on_vehicle
  7: static_person
  8: distractor
  12: reflection

defaults:
  detector: yolov8n
  reid: lmbn_n_duke
