id: mot20

root: "boxmot/engine/eval/trackeval/data/MOT20"
layout: mot
box_type: aabb

splits:
  train: "train"
  test: "test"
  ablation: "ablation"
default_split: ablation

classes:
  1: pedestrian

distractors:
  2: person_on_vehicle
  6: non_mot_vehicle
  7: static_person
  8: distractor
  12: reflection

defaults:
  detector: yolox_x_mot20_ablation
  reid: lmbn_n_duke

download:
  dataset: "hf://Lekim89/MOT20"
