# mot20.yaml
download:
  mot20_url: "https://github.com/mikel-brostrom/boxmot/releases/download/v13.0.9/MOT20-ablation.zip"
  mot20_dest: "boxmot/engine/trackeval/MOT2-ablation.zip"
  overwrite: false

benchmark_cfg:
  source: "MOT20-ablation"
  benchmark: "MOT20-ablation"
  split: "train"
