id: sportsmot

path: "boxmot/engine/trackeval/data/SportsMOT"
split: "val"
train: "train"
val:
test: "test"

layout: mot
box_type: aabb

names:
  1: player

distractors: {}
class_map: {}

download:
  dataset: "hf://MCG-NJU/SportsMOT/dataset"
